### ISSUE TITLE
missing entity_load_single() function

### ISSUE THREAD

**Issue by robertgarrigos** [backdrop-contrib/entity_metadata_wrapper#2]
Rules deleted some entity related functions (https://github.com/backdrop-contrib/rules/commit/5c87a99fad69e2dfa744e07294c3ed963f264a37) because entity_metadata_wrapper is a requirement for rules, but emw module doesn't include entity_load_single() function, which is needed for ubercart.

**Comment by robertgarrigos** [comment]
I solve this by getting back those files in rules and deleting the extra functions  (https://github.com/backdrop-contrib/rules/pull/14) which caused the original issue (https://github.com/backdrop-contrib/rules/issues/8)

**Comment by herbdool** [comment]
Core function entity_load() should probably be used in place of entity_load_single().

**Comment by robertgarrigos** [comment]
yep, that's what I've done finally. thanks
