### ISSUE TITLE
Find a workaround for entity_has_status()

### ISSUE THREAD

**Issue by herbdool** [backdrop-contrib/entity_metadata_wrapper#3]
I get this error when testing out rules but emw also calls it in a number of places:

> Fatal error: Call to undefined function entity_has_status() in /var/www/html/modules/entity_metadata_wrapper/includes/entity.controller.inc on line 946

The function is based on the concept that some entities are defined in code and can't be overridden (but perhaps can be cloned). I wonder if we can adapt it to check if the module defines the entity in config--but even then we can easily override it. So perhaps just use function to display if it's overridden.

**Comment by herbdool** [comment]
I just noticed that entity_ui has entity_ui_entity_has_status() so perhaps this module should rely on that one.

**Comment by docwilmot** [comment]
Fixed
